### ISSUE TITLE
pangoling error

### ISSUE THREAD

**Issue by tamaron1820** [luigifreda/pyslam#101]
when I run main_slam.py, I have this error.
How can I solve this error?
I run with docker on macOS

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/pyslam/viewer3D.py", line 85, in viewer_thread
    self.viewer_init(kViewportWidth, kViewportHeight)
  File "/tmp/pyslam/viewer3D.py", line 93, in viewer_init
    pangolin.CreateWindowAndBind('Map Viewer', w, h)
RuntimeError: Pangolin X11: Unable to retrieve framebuffer options

**Comment by luigifreda** [comment]
Hi,
I am not able to support macOS anymore. Sorry.
In any case, did you try to use the mac branch
https://github.com/luigifreda/pyslam/blob/master/MAC.md
