### ISSUE TITLE
FolderDataset cannot be loaded

### ISSUE THREAD

**Issue by fpczk** [luigifreda/pyslam#27]
I try to run pyslam on a series of images, using a FolderDataset. But I get the following error:

```
# python3 main_vo.py
fps:  None
Traceback (most recent call last):
  File "main_vo.py", line 59, in <module>
    dataset = dataset_factory(config.dataset_settings)
  File "/root/pyslam/dataset.py", line 67, in dataset_factory
    dataset = FolderDataset(path, name, associations, DatasetType.FOLDER)      
  File "/root/pyslam/dataset.py", line 184, in __init__
    self.Ts = 1./self.fps 
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

When looking at *dataset.py*, the reason seems obvious to me: The constructor is defined as :

```
class FolderDataset(Dataset): 
    def __init__(self, path, name, fps=None, associations=None, type=DatasetType.VIDEO): 
        super().__init__(path, name, fps, associations, type)  
        print('fps: ', self.fps)  
...
```
but it's called in the following way:

```
    if type == 'folder':
        dataset = FolderDataset(path, name, associations, DatasetType.FOLDER)   
```

The fps argument is missing here.

**Comment by luigifreda** [comment]
Thanks for finding that issue.
Solved with the new push. You can now set the fps from the config.ini. 
Let me know
