### ISSUE TITLE
Problems with R2D2

### ISSUE THREAD

**Issue by water-wave** [luigifreda/pyslam#67]
Thank you so much for your great work.I can run this program completely.but when i used the R2D2 network and used kitti color dataset,I ran into the following problem.
Traceback (most recent call last):
  File "main_vo.py", line 107, in <module>
    vo.track(img, img_id)  # main VO function 
  File "/home/bob/pyslam-master/visual_odometry.py", line 204, in track
    self.processFirstFrame()
  File "/home/bob/pyslam-master/visual_odometry.py", line 147, in processFirstFrame
    self.kps_ref, self.des_ref = self.feature_tracker.detectAndCompute(self.cur_image)
  File "/home/bob/pyslam-master/feature_tracker.py", line 216, in detectAndCompute
    return self.feature_manager.detectAndCompute(frame, mask) 
  File "/home/bob/pyslam-master/feature_manager.py", line 946, in detectAndCompute
    kps, des = self._feature_detector.detectAndCompute(frame, mask)   
  File "/home/bob/pyslam-master/feature_r2d2.py", line 244, in detectAndCompute
    self.kps, self.des = self.compute_kps_des(frame)            
  File "/home/bob/pyslam-master/feature_r2d2.py", line 212, in compute_kps_des
    img = norm_RGB(img)[None]
  File "/home/bob/anaconda3/envs/py15/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/bob/anaconda3/envs/py15/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 166, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/bob/anaconda3/envs/py15/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 208, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 370, 1226] doesn't match the broadcast shape [3, 370, 1226].please help me.thanks.

**Comment by luigifreda** [comment]
Hi,
the following error means you have to convert the images from RBG (3 channels) to grayscale (1 channel)  
```
RuntimeError: output with shape [1, 370, 1226] doesn't match the broadcast shape [3, 370, 1226].please help me.thanks.
```
